#ifndef M5CORE2_TIME_BOX_GUI_MY_SYMBOLS_HPP_
#define M5CORE2_TIME_BOX_GUI_MY_SYMBOLS_HPP_

#define MY_SYMBOL_CLOCK "\xEF\x80\x97"
#define MY_SYMBOL_LOCAL "\xEF\x8F\x85"

#endif // M5CORE2_TIME_BOX_GUI_MY_SYMBOLS_HPP_